/**
 * PDF Export Utility for HomeOwner Guardian
 * Generates professional PDF reports for various Guardian features
 */

export interface PDFReportData {
    projectName: string;
    builderName: string;
    contractValue: number;
    generatedDate: string;
}

export interface DefectReportItem {
    title: string;
    location: string;
    severity: string;
    status: string;
    reportedDate: string;
    description: string;
}

export interface VariationReportItem {
    title: string;
    description: string;
    amount: number;
    status: string;
    date: string;
}

export interface PaymentMilestone {
    stage: string;
    percentage: number;
    amount: number;
    status: string;
    dueDate: string;
}

/**
 * Format currency
 */
function formatCurrency(amount: number): string {
    return new Intl.NumberFormat("en-AU", {
        style: "currency",
        currency: "AUD",
        minimumFractionDigits: 0,
    }).format(amount);
}

/**
 * Format date
 */
function formatDate(dateStr: string): string {
    return new Date(dateStr).toLocaleDateString("en-AU", {
        day: "numeric",
        month: "long",
        year: "numeric",
    });
}

/**
 * Generate Project Summary PDF content
 */
export function generateProjectSummaryPDF(
    project: PDFReportData & {
        address: string;
        currentStage: string;
        progress: number;
        openDefects: number;
        pendingVariations: number;
        totalVariationValue: number;
    }
): string {
    return `
═══════════════════════════════════════════════════════════════
                    PROJECT SUMMARY REPORT
═══════════════════════════════════════════════════════════════

PROJECT DETAILS
───────────────────────────────────────────────────────────────
Project Name:       ${project.projectName}
Address:            ${project.address}
Builder:            ${project.builderName}
Contract Value:     ${formatCurrency(project.contractValue)}
Report Date:        ${formatDate(project.generatedDate)}

CONSTRUCTION PROGRESS
───────────────────────────────────────────────────────────────
Current Stage:      ${project.currentStage}
Overall Progress:   ${project.progress}%

[${"█".repeat(Math.floor(project.progress / 5))}${"░".repeat(20 - Math.floor(project.progress / 5))}]

KEY METRICS
───────────────────────────────────────────────────────────────
Open Defects:           ${project.openDefects}
Pending Variations:     ${project.pendingVariations}
Total Variation Value:  ${formatCurrency(project.totalVariationValue)}

═══════════════════════════════════════════════════════════════
Generated by HomeOwner Guardian | ${formatDate(new Date().toISOString())}
═══════════════════════════════════════════════════════════════
`.trim();
}

/**
 * Generate Defect List PDF content
 */
export function generateDefectListPDF(
    project: PDFReportData,
    defects: DefectReportItem[]
): string {
    const openDefects = defects.filter(d => d.status !== "verified");
    const criticalCount = defects.filter(d => d.severity === "critical").length;

    let content = `
═══════════════════════════════════════════════════════════════
                      DEFECT REPORT
═══════════════════════════════════════════════════════════════

PROJECT: ${project.projectName}
BUILDER: ${project.builderName}
DATE:    ${formatDate(project.generatedDate)}

SUMMARY
───────────────────────────────────────────────────────────────
Total Defects:      ${defects.length}
Open Defects:       ${openDefects.length}
Critical Items:     ${criticalCount}

DEFECT LIST
───────────────────────────────────────────────────────────────
`;

    defects.forEach((defect, index) => {
        content += `
${index + 1}. ${defect.title.toUpperCase()}
   Location:    ${defect.location}
   Severity:    ${defect.severity.toUpperCase()}
   Status:      ${defect.status}
   Reported:    ${formatDate(defect.reportedDate)}
   Description: ${defect.description}
`;
    });

    content += `
═══════════════════════════════════════════════════════════════
This report serves as formal documentation of outstanding defects.
Please address all items before proceeding with further payments.
═══════════════════════════════════════════════════════════════
Generated by HomeOwner Guardian
`;

    return content.trim();
}

/**
 * Generate Variation Report PDF content
 */
export function generateVariationReportPDF(
    project: PDFReportData,
    variations: VariationReportItem[]
): string {
    const totalValue = variations.reduce((sum, v) => sum + v.amount, 0);
    const variationPercentage = ((totalValue / project.contractValue) * 100).toFixed(1);

    let content = `
═══════════════════════════════════════════════════════════════
                    VARIATION REPORT
═══════════════════════════════════════════════════════════════

PROJECT: ${project.projectName}
BUILDER: ${project.builderName}
CONTRACT VALUE: ${formatCurrency(project.contractValue)}
DATE: ${formatDate(project.generatedDate)}

SUMMARY
───────────────────────────────────────────────────────────────
Total Variations:       ${variations.length}
Total Value:            ${formatCurrency(totalValue)}
% of Contract:          ${variationPercentage}%

${parseFloat(variationPercentage) > 10 ? "⚠️ WARNING: Variations exceed 10% of contract value" : ""}
${parseFloat(variationPercentage) > 15 ? "🚨 CRITICAL: Variations exceed 15% - review recommended" : ""}

VARIATION DETAILS
───────────────────────────────────────────────────────────────
`;

    variations.forEach((variation, index) => {
        content += `
${index + 1}. ${variation.title}
   Description: ${variation.description}
   Amount:      ${formatCurrency(variation.amount)}
   Status:      ${variation.status}
   Date:        ${formatDate(variation.date)}
`;
    });

    content += `
═══════════════════════════════════════════════════════════════
IMPORTANT: All variations should be agreed in writing before work
commences. Keep signed copies of all variation documents.
═══════════════════════════════════════════════════════════════
Generated by HomeOwner Guardian
`;

    return content.trim();
}

/**
 * Generate Payment Schedule PDF content
 */
export function generatePaymentSchedulePDF(
    project: PDFReportData,
    payments: PaymentMilestone[]
): string {
    const paidAmount = payments
        .filter(p => p.status === "paid")
        .reduce((sum, p) => sum + p.amount, 0);
    const remainingAmount = project.contractValue - paidAmount;

    let content = `
═══════════════════════════════════════════════════════════════
                   PAYMENT SCHEDULE
═══════════════════════════════════════════════════════════════

PROJECT: ${project.projectName}
BUILDER: ${project.builderName}
CONTRACT VALUE: ${formatCurrency(project.contractValue)}
DATE: ${formatDate(project.generatedDate)}

PAYMENT SUMMARY
───────────────────────────────────────────────────────────────
Total Contract:     ${formatCurrency(project.contractValue)}
Amount Paid:        ${formatCurrency(paidAmount)}
Remaining:          ${formatCurrency(remainingAmount)}

PAYMENT MILESTONES
───────────────────────────────────────────────────────────────
`;

    payments.forEach((payment, index) => {
        const statusIcon = payment.status === "paid" ? "✓" : payment.status === "due" ? "!" : " ";
        content += `
[${statusIcon}] ${payment.stage}
    Percentage:  ${payment.percentage}%
    Amount:      ${formatCurrency(payment.amount)}
    Status:      ${payment.status.toUpperCase()}
    Due Date:    ${payment.dueDate ? formatDate(payment.dueDate) : "TBD"}
`;
    });

    content += `
═══════════════════════════════════════════════════════════════
REMINDER: Always ensure required certificates are received
before releasing any progress payments.
═══════════════════════════════════════════════════════════════
Generated by HomeOwner Guardian
`;

    return content.trim();
}

/**
 * Generate Fair Trading Dispute Package
 */
export function generateDisputePackagePDF(
    project: PDFReportData,
    defects: DefectReportItem[],
    variations: VariationReportItem[],
    timeline: { date: string; event: string }[]
): string {
    const openDefects = defects.filter(d => d.status !== "verified");

    return `
═══════════════════════════════════════════════════════════════
               NSW FAIR TRADING DISPUTE PACKAGE
               HOME BUILDING COMPENSATION FUND
═══════════════════════════════════════════════════════════════

HOMEOWNER DETAILS
───────────────────────────────────────────────────────────────
[To be completed by homeowner]
Name: _________________________________
Address: _________________________________
Phone: _________________________________
Email: _________________________________

PROJECT DETAILS
───────────────────────────────────────────────────────────────
Project Address:    ${project.projectName}
Builder Name:       ${project.builderName}
Contract Value:     ${formatCurrency(project.contractValue)}
Contract Date:      [Add contract date]

NATURE OF DISPUTE
───────────────────────────────────────────────────────────────
[ ] Defective work
[ ] Incomplete work
[ ] Variations dispute
[ ] Delay in completion
[ ] Other: _________________________________

OUTSTANDING DEFECTS (${openDefects.length} items)
───────────────────────────────────────────────────────────────
${openDefects.map((d, i) => `${i + 1}. ${d.title} - ${d.location} (${d.severity})`).join("\n")}

COMMUNICATION TIMELINE
───────────────────────────────────────────────────────────────
${timeline.map(t => `${formatDate(t.date)}: ${t.event}`).join("\n")}

SUPPORTING DOCUMENTS ATTACHED
───────────────────────────────────────────────────────────────
[ ] Copy of building contract
[ ] All variation orders
[ ] Defect notification letters
[ ] Photo evidence
[ ] Correspondence with builder
[ ] Relevant certificates

═══════════════════════════════════════════════════════════════
For assistance, contact:
NSW Fair Trading: 13 32 20
HBCF Claims: 1800 110 877
NCAT (Tribunal): 1300 006 228
═══════════════════════════════════════════════════════════════
Generated by HomeOwner Guardian | ${formatDate(new Date().toISOString())}
`.trim();
}

/**
 * Download content as text file
 */
export function downloadAsTextFile(content: string, filename: string): void {
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

/**
 * Print content (opens print dialog)
 */
export function printContent(content: string, title: string): void {
    const printWindow = window.open("", "_blank");
    if (printWindow) {
        printWindow.document.write(`
            <!DOCTYPE html>
            <html>
            <head>
                <title>${title}</title>
                <style>
                    body {
                        font-family: 'Courier New', monospace;
                        white-space: pre-wrap;
                        padding: 40px;
                        line-height: 1.4;
                    }
                    @media print {
                        body { padding: 20px; }
                    }
                </style>
            </head>
            <body>${content}</body>
            </html>
        `);
        printWindow.document.close();
        printWindow.print();
    }
}
