"use client";

import { useState } from "react";

interface ReportGeneratorProps {
    projectId: string;
    projectName: string;
    builderName: string;
    contractValue: number;
    variations: Array<{
        id: string;
        title: string;
        description: string;
        additional_cost: number;
        status: string;
        created_at: string;
    }>;
    defects: Array<{
        id: string;
        title: string;
        description: string;
        severity: string;
        status: string;
        created_at: string;
    }>;
}

type ReportType = "summary" | "variations" | "defects" | "dispute";
type ExportFormat = "pdf" | "html" | "txt";

const FORMAT_OPTIONS: { id: ExportFormat; name: string; icon: string; description: string }[] = [
    { id: "pdf", name: "PDF", icon: "📄", description: "Best for printing & sharing" },
    { id: "html", name: "HTML", icon: "🌐", description: "Open in browser" },
    { id: "txt", name: "Text", icon: "📝", description: "Plain text format" },
];

export default function ReportGenerator({
    projectId,
    projectName,
    builderName,
    contractValue,
    variations = [],
    defects = [],
}: ReportGeneratorProps) {
    const [generating, setGenerating] = useState(false);
    const [selectedReport, setSelectedReport] = useState<ReportType>("summary");
    const [selectedFormat, setSelectedFormat] = useState<ExportFormat>("pdf");

    const totalVariations = variations.reduce(
        (sum, v) => sum + (v.additional_cost || 0),
        0
    );
    const variationPercent = contractValue > 0
        ? ((totalVariations / contractValue) * 100).toFixed(1)
        : "0";

    const generateReport = async (type: ReportType) => {
        setGenerating(true);

        // Create report content based on type
        let content = "";
        const date = new Date().toLocaleDateString("en-AU", {
            year: "numeric",
            month: "long",
            day: "numeric",
        });

        switch (type) {
            case "summary":
                content = generateSummaryReport(date);
                break;
            case "variations":
                content = generateVariationsReport(date);
                break;
            case "defects":
                content = generateDefectsReport(date);
                break;
            case "dispute":
                content = generateDisputeReport(date);
                break;
        }

        // Create and download the report
        downloadReport(content, type);
        setGenerating(false);
    };

    const generateSummaryReport = (date: string) => {
        return `
================================================================================
                          PROJECT SUMMARY REPORT
================================================================================

Generated: ${date}
Project: ${projectName}
Builder: ${builderName}

--------------------------------------------------------------------------------
                              FINANCIAL SUMMARY
--------------------------------------------------------------------------------

Original Contract Value:     $${contractValue.toLocaleString()}
Total Approved Variations:   $${totalVariations.toLocaleString()}
                             (${variationPercent}% of contract)
Projected Total:             $${(contractValue + totalVariations).toLocaleString()}

--------------------------------------------------------------------------------
                              VARIATIONS SUMMARY
--------------------------------------------------------------------------------

Total Variations Logged:     ${variations.length}
Approved:                    ${variations.filter((v) => v.status === "approved").length}
Pending:                     ${variations.filter((v) => v.status === "pending").length}
Disputed:                    ${variations.filter((v) => v.status === "disputed").length}

--------------------------------------------------------------------------------
                              DEFECTS SUMMARY
--------------------------------------------------------------------------------

Total Defects Logged:        ${defects.length}
Critical:                    ${defects.filter((d) => d.severity === "critical").length}
Major:                       ${defects.filter((d) => d.severity === "major").length}
Minor:                       ${defects.filter((d) => d.severity === "minor").length}
Open:                        ${defects.filter((d) => d.status === "open").length}
Resolved:                    ${defects.filter((d) => d.status === "resolved").length}

================================================================================
                    Generated by HomeOwner Guardian
                        VedaWell Tools © 2026
================================================================================
    `.trim();
    };

    const generateVariationsReport = (date: string) => {
        let report = `
================================================================================
                          VARIATIONS REPORT
================================================================================

Generated: ${date}
Project: ${projectName}
Builder: ${builderName}
Original Contract Value: $${contractValue.toLocaleString()}

================================================================================
                         VARIATION DETAILS
================================================================================
`;

        if (variations.length === 0) {
            report += "\nNo variations recorded.\n";
        } else {
            variations.forEach((v, idx) => {
                report += `
--------------------------------------------------------------------------------
VARIATION #${idx + 1}
--------------------------------------------------------------------------------
Title:       ${v.title || 'Untitled'}
Amount:      $${v.additional_cost?.toLocaleString() || 0}
Status:      ${(v.status || 'pending').toUpperCase()}
Date:        ${new Date(v.created_at).toLocaleDateString("en-AU")}
Description: ${v.description || "N/A"}
`;
            });

            report += `
================================================================================
                              SUMMARY
================================================================================

Total Variations:            ${variations.length}
Total Additional Cost:       $${totalVariations.toLocaleString()}
Percentage of Contract:      ${variationPercent}%

${parseFloat(variationPercent) > 10
                    ? `
⚠️ WARNING: Variations exceed 10% of contract value.
Consider reviewing with an independent building consultant.
`
                    : ""
                }
`;
        }

        report += `
================================================================================
                    Generated by HomeOwner Guardian
                        VedaWell Tools © 2026
================================================================================
    `.trim();

        return report;
    };

    const generateDefectsReport = (date: string) => {
        let report = `
================================================================================
                          DEFECTS REPORT
================================================================================

Generated: ${date}
Project: ${projectName}
Builder: ${builderName}

================================================================================
                         DEFECT DETAILS
================================================================================
`;

        if (defects.length === 0) {
            report += "\nNo defects recorded.\n";
        } else {
            defects.forEach((d, idx) => {
                report += `
--------------------------------------------------------------------------------
DEFECT #${idx + 1}
--------------------------------------------------------------------------------
Title:       ${d.title || 'Untitled'}
Severity:    ${(d.severity || 'minor').toUpperCase()}
Status:      ${(d.status || 'open').toUpperCase()}
Date:        ${d.created_at ? new Date(d.created_at).toLocaleDateString("en-AU") : 'N/A'}
Description: ${d.description || "N/A"}
`;
            });
        }

        report += `
================================================================================
                              SUMMARY
================================================================================

Total Defects:               ${defects.length}
Critical:                    ${defects.filter((d) => d.severity === "critical").length}
Major:                       ${defects.filter((d) => d.severity === "major").length}
Minor:                       ${defects.filter((d) => d.severity === "minor").length}

================================================================================
                    Generated by HomeOwner Guardian
                        VedaWell Tools © 2026
================================================================================
    `.trim();

        return report;
    };

    const generateDisputeReport = (date: string) => {
        return `
================================================================================
                    DISPUTE DOCUMENTATION PACKAGE
                     For NSW Fair Trading / NCAT
================================================================================

Generated: ${date}

================================================================================
                         COMPLAINANT DETAILS
================================================================================

[YOUR NAME]:        ________________________________________________
[YOUR ADDRESS]:     ________________________________________________
[YOUR PHONE]:       ________________________________________________
[YOUR EMAIL]:       ________________________________________________

================================================================================
                          PROJECT DETAILS
================================================================================

Project Name:       ${projectName}
Site Address:       [Insert site address]
Builder Name:       ${builderName}
Builder License #:  [Insert license number - verify at fairtrading.nsw.gov.au]
Contract Date:      [Insert date]
Contract Value:     $${contractValue.toLocaleString()}

================================================================================
                        NATURE OF DISPUTE
================================================================================

[ ] Variations without proper written approval
[ ] Work not completed to standard
[ ] Builder unresponsive / abandonment
[ ] Defects not rectified
[ ] Other: _______________________________

================================================================================
                         FINANCIAL SUMMARY
================================================================================

Original Contract:           $${contractValue.toLocaleString()}
Approved Variations:         $${totalVariations.toLocaleString()}
                             (${variationPercent}% of contract)
Amount in Dispute:           $______________

================================================================================
                       VARIATIONS IN DISPUTE
================================================================================
${variations.filter((v) => v.status === "disputed").length === 0
                ? "\n[List any disputed variations here]\n"
                : variations
                    .filter((v) => v.status === "disputed")
                    .map(
                        (v, i) => `
${i + 1}. ${v.title}
   Amount: $${v.additional_cost?.toLocaleString()}
   Date: ${new Date(v.created_at).toLocaleDateString("en-AU")}
   Issue: ${v.description}
`
                    )
                    .join("")
            }

================================================================================
                         DEFECTS SUMMARY
================================================================================

Total Defects Reported:      ${defects.length}
Outstanding (Open):          ${defects.filter((d) => d.status === "open").length}

${defects
                .filter((d) => d.status === "open")
                .map(
                    (d, i) => `
${i + 1}. [${(d.severity || 'minor').toUpperCase()}] ${d.title || 'Untitled'}
   Description: ${d.description}
   Logged: ${new Date(d.created_at).toLocaleDateString("en-AU")}
`
                )
                .join("")}

================================================================================
                         ATTACHMENTS CHECKLIST
================================================================================

[ ] Copy of Building Contract
[ ] HBCF/Home Warranty Insurance Certificate
[ ] All Variation Orders (signed and unsigned)
[ ] Photographs of defects (dated)
[ ] All correspondence with builder
[ ] Inspection reports (if any)
[ ] Payment records / invoices

================================================================================
                          NEXT STEPS
================================================================================

1. Complete this form with your details
2. Gather all attachments listed above
3. Lodge complaint with NSW Fair Trading:
   - Online: fairtrading.nsw.gov.au
   - Phone: 13 32 20
4. If unresolved, apply to NCAT (ncat.nsw.gov.au)

================================================================================
                    Generated by HomeOwner Guardian
                        VedaWell Tools © 2026
================================================================================
    `.trim();
    };

    const downloadReport = (content: string, type: string) => {
        const baseName = `${projectName.replace(/\s+/g, "_")}_${type}_report_${new Date().toISOString().split("T")[0]}`;
        const title = `${projectName} - ${type.charAt(0).toUpperCase() + type.slice(1)} Report`;

        switch (selectedFormat) {
            case "pdf":
                // Open print dialog - user can save as PDF
                printReport(content, title);
                break;
            case "html":
                downloadAsHTML(content, `${baseName}.html`, title);
                break;
            case "txt":
                downloadAsText(content, `${baseName}.txt`);
                break;
        }
    };

    const printReport = (content: string, title: string) => {
        const printWindow = window.open("", "_blank");
        if (printWindow) {
            printWindow.document.write(`
                <!DOCTYPE html>
                <html>
                <head>
                    <title>${title}</title>
                    <style>
                        body {
                            font-family: 'Courier New', monospace;
                            white-space: pre-wrap;
                            padding: 40px;
                            line-height: 1.4;
                        }
                        @media print {
                            body { padding: 20px; }
                        }
                    </style>
                </head>
                <body>${content}</body>
                </html>
            `);
            printWindow.document.close();
            printWindow.print();
        }
    };

    const downloadAsHTML = (content: string, filename: string, title: string) => {
        const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
        body {
            font-family: 'Courier New', monospace;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            background: #f5f5f5;
        }
        pre {
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            white-space: pre-wrap;
            word-wrap: break-word;
        }
        @media print {
            body { margin: 0; padding: 20px; background: white; }
            pre { box-shadow: none; }
        }
    </style>
</head>
<body>
    <pre>${content.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
</body>
</html>`;
        const blob = new Blob([htmlContent], { type: "text/html;charset=utf-8" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const downloadAsText = (content: string, filename: string) => {
        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="space-y-6">
            <div>
                <h2 className="text-2xl font-bold">📊 Generate Reports</h2>
                <p className="text-muted-foreground">
                    Download reports for your records or Fair Trading disputes.
                </p>
            </div>

            {/* Format Selector */}
            <div className="p-4 bg-gray-50 dark:bg-gray-800/50 border border-border rounded-xl">
                <p className="text-sm font-medium mb-3 text-gray-700 dark:text-gray-300">📁 Select Download Format:</p>
                <div className="flex gap-2 flex-wrap">
                    {FORMAT_OPTIONS.map((format) => (
                        <button
                            key={format.id}
                            onClick={() => setSelectedFormat(format.id)}
                            className={`px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition-all ${selectedFormat === format.id
                                    ? "bg-primary text-white ring-2 ring-primary ring-offset-2"
                                    : "bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-600"
                                }`}
                        >
                            <span>{format.icon}</span>
                            <span>{format.name}</span>
                        </button>
                    ))}
                </div>
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">
                    {FORMAT_OPTIONS.find(f => f.id === selectedFormat)?.description}
                    {selectedFormat === "pdf" && " — Opens print dialog where you can 'Save as PDF'"}
                </p>
            </div>

            <div className="grid md:grid-cols-2 gap-4">
                {/* Summary Report */}
                <div className="p-6 bg-card border border-border rounded-xl">
                    <div className="flex items-start gap-3">
                        <span className="text-3xl">📋</span>
                        <div className="flex-1">
                            <h3 className="font-bold">Project Summary</h3>
                            <p className="text-sm text-muted-foreground mt-1">
                                Overview of contract value, variations total, and defects count.
                            </p>
                            <button
                                onClick={() => generateReport("summary")}
                                disabled={generating}
                                className="mt-3 px-4 py-2 bg-primary text-white rounded-lg text-sm font-medium disabled:opacity-50"
                            >
                                {generating ? "Generating..." : "Download Summary"}
                            </button>
                        </div>
                    </div>
                </div>

                {/* Variations Report */}
                <div className="p-6 bg-card border border-border rounded-xl">
                    <div className="flex items-start gap-3">
                        <span className="text-3xl">💰</span>
                        <div className="flex-1">
                            <h3 className="font-bold">Variations Report</h3>
                            <p className="text-sm text-muted-foreground mt-1">
                                Detailed list of all {variations.length} variations with costs and status.
                            </p>
                            <button
                                onClick={() => generateReport("variations")}
                                disabled={generating}
                                className="mt-3 px-4 py-2 bg-primary text-white rounded-lg text-sm font-medium disabled:opacity-50"
                            >
                                {generating ? "Generating..." : "Download Variations"}
                            </button>
                        </div>
                    </div>
                </div>

                {/* Defects Report */}
                <div className="p-6 bg-card border border-border rounded-xl">
                    <div className="flex items-start gap-3">
                        <span className="text-3xl">🔧</span>
                        <div className="flex-1">
                            <h3 className="font-bold">Defects Report</h3>
                            <p className="text-sm text-muted-foreground mt-1">
                                Complete log of {defects.length} defects with severity and status.
                            </p>
                            <button
                                onClick={() => generateReport("defects")}
                                disabled={generating}
                                className="mt-3 px-4 py-2 bg-primary text-white rounded-lg text-sm font-medium disabled:opacity-50"
                            >
                                {generating ? "Generating..." : "Download Defects"}
                            </button>
                        </div>
                    </div>
                </div>

                {/* Dispute Package */}
                <div className="p-6 bg-red-50 border border-red-200 rounded-xl">
                    <div className="flex items-start gap-3">
                        <span className="text-3xl">⚖️</span>
                        <div className="flex-1">
                            <h3 className="font-bold text-red-800">Fair Trading Dispute Package</h3>
                            <p className="text-sm text-red-700 mt-1">
                                Pre-formatted template for NSW Fair Trading or NCAT complaints.
                            </p>
                            <button
                                onClick={() => generateReport("dispute")}
                                disabled={generating}
                                className="mt-3 px-4 py-2 bg-red-600 text-white rounded-lg text-sm font-medium disabled:opacity-50 hover:bg-red-700"
                            >
                                {generating ? "Generating..." : "Generate Dispute Package"}
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            {/* Info Box */}
            <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
                <h4 className="font-bold text-blue-800 mb-2">📝 About These Reports</h4>
                <ul className="text-sm text-blue-700 space-y-1">
                    <li>• Reports are generated as plain text files for maximum compatibility</li>
                    <li>• The Dispute Package is formatted for NSW Fair Trading submission</li>
                    <li>• Always attach photos, contracts, and certificates as supporting evidence</li>
                    <li>• Keep copies of all reports for your records</li>
                </ul>
            </div>
        </div>
    );
}
