import { NextRequest, NextResponse } from "next/server";
import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { PDFDocument, rgb, StandardFonts, PDFFont, PDFPage } from "pdf-lib";

async function getSupabase() {
    const cookieStore = await cookies();
    return createServerClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
        {
            cookies: {
                getAll: () => cookieStore.getAll(),
                setAll: () => { },
            },
        }
    );
}

// Colors
const TEAL = rgb(13 / 255, 110 / 255, 110 / 255);
const BLACK = rgb(0, 0, 0);
const GRAY = rgb(0.4, 0.45, 0.5);
const RED = rgb(0.86, 0.15, 0.15);
const GREEN = rgb(0.13, 0.55, 0.13);
const AMBER = rgb(0.85, 0.55, 0.0);
const PAGE_W = 595;
const PAGE_H = 842;
const MARGIN = 50;
const LINE_H = 16;

// NSW standard payment schedule
const STAGE_PAYMENTS = [
    { stage: "Deposit", pct: 5 },
    { stage: "Base/Slab", pct: 15 },
    { stage: "Frame", pct: 20 },
    { stage: "Lockup", pct: 25 },
    { stage: "Fixing", pct: 20 },
    { stage: "Completion", pct: 15 },
];

type ReportType = "full" | "defects" | "variations" | "payments" | "dispute" | "summary";

/** Helper class for drawing on multi-page PDFs */
class PDFWriter {
    pdf: PDFDocument;
    page: PDFPage;
    y: number;
    font: PDFFont;
    fontBold: PDFFont;

    constructor(pdf: PDFDocument, font: PDFFont, fontBold: PDFFont) {
        this.pdf = pdf;
        this.font = font;
        this.fontBold = fontBold;
        this.page = pdf.addPage([PAGE_W, PAGE_H]);
        this.y = PAGE_H - MARGIN;
    }

    addPage() {
        this.page = this.pdf.addPage([PAGE_W, PAGE_H]);
        this.y = PAGE_H - MARGIN;
    }

    checkSpace(needed: number) {
        if (this.y - needed < MARGIN) this.addPage();
    }

    text(text: string, x: number, opts: { bold?: boolean; size?: number; color?: ReturnType<typeof rgb> } = {}) {
        const f = opts.bold ? this.fontBold : this.font;
        const s = opts.size || 10;
        const c = opts.color || BLACK;
        const maxW = PAGE_W - x - MARGIN;
        let t = text;
        while (f.widthOfTextAtSize(t, s) > maxW && t.length > 3) {
            t = t.slice(0, -4) + "...";
        }
        this.page.drawText(t, { x, y: this.y, size: s, font: f, color: c });
    }

    line(color = GRAY, thickness = 0.5) {
        this.page.drawLine({ start: { x: MARGIN, y: this.y }, end: { x: PAGE_W - MARGIN, y: this.y }, thickness, color });
    }

    gap(h = LINE_H) { this.y -= h; }

    header(title: string, subtitle: string) {
        this.text("HOMEOWNER GUARDIAN", MARGIN, { bold: true, size: 18, color: TEAL });
        this.gap(24);
        this.text(subtitle, MARGIN, { bold: true, size: 13, color: GRAY });
        this.gap(8);
        this.line(TEAL, 1);
        this.gap(20);
    }

    projectDetails(project: Record<string, unknown>) {
        this.text("Project Details", MARGIN, { bold: true, size: 12, color: TEAL });
        this.gap();
        const rows = [
            ["Project Name", project.name],
            ["Builder", project.builder_name || "—"],
            ["Address", project.address || "—"],
            ["Contract Value", project.contract_value ? `$${Number(project.contract_value).toLocaleString()}` : "—"],
            ["State", project.state || "—"],
            ["Status", project.status || "—"],
            ["Report Date", new Date().toLocaleDateString("en-AU", { year: "numeric", month: "long", day: "numeric" })],
        ];
        for (const [label, value] of rows) {
            this.text(`${label}:`, MARGIN, { bold: true, size: 9, color: GRAY });
            this.text(String(value), MARGIN + 110, { size: 9 });
            this.gap();
        }
        this.gap(10);
    }

    sectionTitle(title: string, color = TEAL) {
        this.checkSpace(40);
        this.line();
        this.gap(16);
        this.text(title, MARGIN, { bold: true, size: 12, color });
        this.gap();
    }

    footer() {
        this.checkSpace(40);
        this.gap(10);
        this.line();
        this.gap(14);
        this.text("Generated by VedaWell HomeOwner Guardian — vedawellapp.com", MARGIN, { size: 8, color: GRAY });
        this.gap(12);
        this.text("This report is for record-keeping purposes. Consult a building inspector or solicitor for legal advice.", MARGIN, { size: 7, color: GRAY });
    }
}

function fmtDate(d: string | null | undefined): string {
    if (!d) return "—";
    try { return new Date(d).toLocaleDateString("en-AU"); } catch { return "—"; }
}

function fmtCurrency(n: number): string {
    return `$${n.toLocaleString("en-AU")}`;
}

/**
 * PDF Export API — generates branded PDF reports for Guardian projects.
 * Pro-only feature.
 *
 * GET /api/guardian/export-pdf?projectId=xxx&type=full|defects|variations|payments|dispute|summary
 */
export async function GET(req: NextRequest) {
    const projectId = req.nextUrl.searchParams.get("projectId");
    const reportType = (req.nextUrl.searchParams.get("type") || "full") as ReportType;

    if (!projectId) {
        return NextResponse.json({ error: "projectId required" }, { status: 400 });
    }

    const supabase = await getSupabase();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Check pro access
    const { data: profile } = await supabase
        .from("profiles")
        .select("subscription_tier, is_admin, trial_ends_at")
        .eq("id", user.id)
        .single();

    const tier = profile?.subscription_tier || "free";
    const isAdmin = profile?.is_admin === true;
    const trialActive = tier === "trial" && profile?.trial_ends_at && new Date(profile.trial_ends_at) > new Date();
    const hasPro = tier === "guardian_pro" || isAdmin || trialActive;

    if (!hasPro) {
        return NextResponse.json({ error: "PDF export requires Guardian Pro" }, { status: 403 });
    }

    // Fetch project
    const { data: project } = await supabase
        .from("projects")
        .select("*")
        .eq("id", projectId)
        .eq("user_id", user.id)
        .single();

    if (!project) {
        return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    // Fetch all data in parallel
    const [defectsRes, variationsRes, stagesRes, commsRes, inspectionsRes] = await Promise.all([
        supabase.from("defects").select("*").eq("project_id", projectId).order("created_at", { ascending: false }),
        supabase.from("variations").select("*").eq("project_id", projectId).order("created_at", { ascending: false }),
        supabase.from("stages").select("*").eq("project_id", projectId).order("created_at", { ascending: true }),
        supabase.from("communication_log").select("*").eq("project_id", projectId).order("date", { ascending: true }),
        supabase.from("inspections").select("*").eq("project_id", projectId).order("created_at", { ascending: true }),
    ]);

    const defects = defectsRes.data || [];
    const variations = variationsRes.data || [];
    const stages = stagesRes.data || [];
    const comms = commsRes.data || [];
    const inspections = inspectionsRes.data || [];
    const contractValue = Number(project.contract_value) || 0;

    // Build PDF
    const pdf = await PDFDocument.create();
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
    const w = new PDFWriter(pdf, font, fontBold);

    const REPORT_TITLES: Record<ReportType, string> = {
        full: "Complete Project Report",
        defects: "Defect Report",
        variations: "Variation Report",
        payments: "Payment Schedule",
        dispute: "Fair Trading Dispute Package",
        summary: "Project Summary Report",
    };

    w.header("HOMEOWNER GUARDIAN", REPORT_TITLES[reportType]);
    w.projectDetails(project);

    // ── Summary section ──
    if (reportType === "summary" || reportType === "full") {
        const openDefects = defects.filter((d: Record<string, unknown>) => d.status !== "verified" && d.status !== "rectified").length;
        const completedStages = stages.filter((s: Record<string, unknown>) => s.status === "completed").length;
        const activeStage = stages.find((s: Record<string, unknown>) => s.status !== "completed");
        const progress = stages.length > 0 ? Math.round((completedStages / stages.length) * 100) : 0;
        const totalVarCost = variations.reduce((sum: number, v: Record<string, unknown>) => sum + (Number(v.additional_cost) || 0), 0);

        w.sectionTitle("Project Summary");
        w.text(`Current Stage:`, MARGIN, { bold: true, size: 9, color: GRAY });
        w.text((activeStage?.name as string) || "Not started", MARGIN + 110, { size: 9 });
        w.gap();
        w.text(`Overall Progress:`, MARGIN, { bold: true, size: 9, color: GRAY });
        w.text(`${progress}%`, MARGIN + 110, { size: 9 });
        w.gap();
        w.text(`Stages Completed:`, MARGIN, { bold: true, size: 9, color: GRAY });
        w.text(`${completedStages} of ${stages.length}`, MARGIN + 110, { size: 9 });
        w.gap();
        w.text(`Open Defects:`, MARGIN, { bold: true, size: 9, color: GRAY });
        w.text(`${openDefects}`, MARGIN + 110, { size: 9, color: openDefects > 0 ? RED : GREEN });
        w.gap();
        w.text(`Total Variations:`, MARGIN, { bold: true, size: 9, color: GRAY });
        w.text(`${variations.length} (${fmtCurrency(totalVarCost)})`, MARGIN + 110, { size: 9 });
        w.gap();
        w.text(`Inspections:`, MARGIN, { bold: true, size: 9, color: GRAY });
        w.text(`${inspections.length}`, MARGIN + 110, { size: 9 });
        w.gap(10);
    }

    // ── Defects section ──
    if (reportType === "defects" || reportType === "full" || reportType === "dispute") {
        const openDefects = defects.filter((d: Record<string, unknown>) => d.status !== "verified" && d.status !== "rectified");
        const defectsToShow = reportType === "dispute" ? openDefects : defects;
        const criticalCount = defectsToShow.filter((d: Record<string, unknown>) => d.severity === "critical").length;

        w.sectionTitle(`Defects (${defectsToShow.length})`, RED);
        if (criticalCount > 0) {
            w.text(`CRITICAL ITEMS: ${criticalCount}`, MARGIN, { bold: true, size: 10, color: RED });
            w.gap();
        }

        if (defectsToShow.length > 0) {
            for (const defect of defectsToShow) {
                w.checkSpace(80);
                w.text(`${defect.title || "Untitled Defect"}`, MARGIN, { bold: true, size: 10 });
                w.gap();
                w.text(`Status: ${defect.status || "open"}`, MARGIN + 10, { size: 9, color: GRAY });
                w.text(`Severity: ${defect.severity || "—"}`, MARGIN + 160, { size: 9, color: defect.severity === "critical" ? RED : GRAY });
                w.gap();
                if (defect.description) {
                    const desc = defect.description.length > 120 ? defect.description.slice(0, 117) + "..." : defect.description;
                    w.text(desc, MARGIN + 10, { size: 9, color: GRAY });
                    w.gap();
                }
                if (defect.location) {
                    w.text(`Location: ${defect.location}`, MARGIN + 10, { size: 9, color: GRAY });
                    w.gap();
                }
                w.text(`Reported: ${fmtDate(defect.created_at)}`, MARGIN + 10, { size: 9, color: GRAY });
                w.gap(LINE_H + 6);
            }
        } else {
            w.text("No defects recorded.", MARGIN + 10, { size: 9, color: GRAY });
            w.gap();
        }
    }

    // ── Variations section ──
    if (reportType === "variations" || reportType === "full" || reportType === "dispute") {
        const totalValue = variations.reduce((sum: number, v: Record<string, unknown>) => sum + (Number(v.additional_cost) || 0), 0);
        const varPct = contractValue > 0 ? ((totalValue / contractValue) * 100).toFixed(1) : "0";

        w.sectionTitle(`Variations (${variations.length})`);
        w.text(`Total Value: ${fmtCurrency(totalValue)}`, MARGIN, { bold: true, size: 9, color: GRAY });
        w.text(`${varPct}% of contract`, MARGIN + 200, { size: 9, color: parseFloat(varPct) > 10 ? RED : GRAY });
        w.gap();

        if (parseFloat(varPct) > 15) {
            w.text("WARNING: Variations exceed 15% of contract value — review strongly recommended", MARGIN, { bold: true, size: 9, color: RED });
            w.gap();
        } else if (parseFloat(varPct) > 10) {
            w.text("CAUTION: Variations exceed 10% of contract value", MARGIN, { bold: true, size: 9, color: AMBER });
            w.gap();
        }

        if (variations.length > 0) {
            for (const v of variations) {
                w.checkSpace(60);
                w.text(v.description || v.title || "Untitled Variation", MARGIN, { bold: true, size: 10 });
                w.gap();
                const cost = v.additional_cost ? fmtCurrency(Number(v.additional_cost)) : "$0";
                w.text(`Cost: ${cost}`, MARGIN + 10, { size: 9, color: GRAY });
                w.text(`Status: ${v.status || "pending"}`, MARGIN + 160, { size: 9, color: GRAY });
                w.gap();
                w.text(`Date: ${fmtDate(v.created_at)}`, MARGIN + 10, { size: 9, color: GRAY });
                w.gap(LINE_H + 6);
            }
        } else {
            w.text("No variations recorded.", MARGIN + 10, { size: 9, color: GRAY });
            w.gap();
        }
    }

    // ── Payments section ──
    if (reportType === "payments" || reportType === "full") {
        w.sectionTitle("Payment Schedule");

        const paidAmount = STAGE_PAYMENTS.reduce((sum, sp) => {
            const match = stages.find((s: Record<string, unknown>) =>
                (s.name as string).toLowerCase().includes(sp.stage.toLowerCase().replace("/", ""))
            );
            return sum + (match?.status === "completed" ? Math.round(contractValue * sp.pct / 100) : 0);
        }, 0);
        const remaining = contractValue - paidAmount;

        w.text(`Total Contract:`, MARGIN, { bold: true, size: 9, color: GRAY });
        w.text(fmtCurrency(contractValue), MARGIN + 110, { size: 9 });
        w.gap();
        w.text(`Amount Paid:`, MARGIN, { bold: true, size: 9, color: GRAY });
        w.text(fmtCurrency(paidAmount), MARGIN + 110, { size: 9, color: GREEN });
        w.gap();
        w.text(`Remaining:`, MARGIN, { bold: true, size: 9, color: GRAY });
        w.text(fmtCurrency(remaining), MARGIN + 110, { size: 9 });
        w.gap(10);

        // Payment milestones table
        for (const sp of STAGE_PAYMENTS) {
            w.checkSpace(20);
            const match = stages.find((s: Record<string, unknown>) =>
                (s.name as string).toLowerCase().includes(sp.stage.toLowerCase().replace("/", ""))
            );
            const isPaid = match?.status === "completed";
            const icon = isPaid ? "[PAID]" : "[    ]";
            const amount = Math.round(contractValue * sp.pct / 100);

            w.text(icon, MARGIN, { bold: true, size: 9, color: isPaid ? GREEN : GRAY });
            w.text(`${sp.stage} (${sp.pct}%)`, MARGIN + 45, { size: 9 });
            w.text(fmtCurrency(amount), MARGIN + 200, { size: 9, color: isPaid ? GREEN : BLACK });
            w.gap();
        }

        w.gap(6);
        w.text("Always ensure required certificates are received before releasing progress payments.", MARGIN, { size: 8, color: GRAY });
        w.gap();
    }

    // ── Dispute package extras ──
    if (reportType === "dispute") {
        w.sectionTitle("Communication Timeline");
        if (comms.length > 0) {
            for (const c of comms) {
                w.checkSpace(20);
                w.text(`${fmtDate(c.date)}: ${c.summary || "—"}`, MARGIN, { size: 9 });
                w.gap();
            }
        } else {
            w.text("No communication log entries recorded.", MARGIN + 10, { size: 9, color: GRAY });
            w.gap();
        }

        w.sectionTitle("Fair Trading Information");
        w.text("NSW Fair Trading: 13 32 20", MARGIN, { bold: true, size: 10 });
        w.gap();
        w.text("HBCF Claims: 1800 110 877", MARGIN, { bold: true, size: 10 });
        w.gap();
        w.text("NCAT (Tribunal): 1300 006 228", MARGIN, { bold: true, size: 10 });
        w.gap(10);
        w.text("Supporting documents to include:", MARGIN, { bold: true, size: 9, color: GRAY });
        w.gap();
        const docs = ["Copy of building contract", "All variation orders", "Defect notification letters",
            "Photo evidence (timestamped)", "Correspondence with builder", "Relevant certificates"];
        for (const doc of docs) {
            w.text(`[ ] ${doc}`, MARGIN + 10, { size: 9 });
            w.gap();
        }
    }

    // ── Inspections section (full report only) ──
    if (reportType === "full" && inspections.length > 0) {
        w.sectionTitle(`Inspections (${inspections.length})`);
        for (const insp of inspections) {
            w.checkSpace(30);
            w.text(insp.stage_name || insp.type || "Inspection", MARGIN, { bold: true, size: 10 });
            const statusColor = insp.status === "passed" ? GREEN : insp.status === "failed" ? RED : GRAY;
            w.text(`Status: ${insp.status || "pending"}`, MARGIN + 200, { size: 9, color: statusColor });
            w.gap();
            if (insp.scheduled_date) {
                w.text(`Scheduled: ${fmtDate(insp.scheduled_date)}`, MARGIN + 10, { size: 9, color: GRAY });
                w.gap();
            }
        }
    }

    w.footer();

    const pdfBytes = await pdf.save();
    const typeLabel = REPORT_TITLES[reportType].replace(/\s+/g, "-").toLowerCase();

    return new NextResponse(Buffer.from(pdfBytes), {
        status: 200,
        headers: {
            "Content-Type": "application/pdf",
            "Content-Disposition": `attachment; filename="guardian-${typeLabel}-${project.name.replace(/[^a-zA-Z0-9]/g, "-")}.pdf"`,
        },
    });
}
